(() => {
  'use strict';
  const cfg = window.APP_CONFIG || {};
  const configured = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_URL.includes('TU-PROYECTO') && !cfg.SUPABASE_ANON_KEY.includes('TU-ANON');
  const S = { sb:null, session:null, profile:null, services:[], materials:[], stocks:[], profiles:[], history:[], tab:'dashboard', adminService:null, drafts:new Map(), channel:null, timer:null, busy:false };
  const E = {}; const M = {};
  const dtf = new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'});

  document.addEventListener('DOMContentLoaded', init);

  async function init(){
    document.querySelectorAll('[id]').forEach(x=>E[x.id]=x);
    M.service = new bootstrap.Modal(E.serviceModal); M.material = new bootstrap.Modal(E.materialModal); M.user = new bootstrap.Modal(E.userModal); M.toast = new bootstrap.Toast(E.appToast,{delay:3200});
    bind(); document.title = cfg.APP_NAME || 'Stock Clean It'; E.appTitle.textContent = document.title;
    if(!configured){ E.loadingScreen.classList.add('d-none'); E.authView.classList.remove('d-none'); E.setupWarning.classList.remove('d-none'); E.loginButton.disabled=true; return; }
    S.sb = supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    S.sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>handleSession(s),0));
    const {data,error}=await S.sb.auth.getSession(); if(error) toast('No se pudo recuperar la sesión.','error'); await handleSession(data?.session||null);
  }

  function bind(){
    E.loginForm.addEventListener('submit',login); E.logoutButton.addEventListener('click',()=>S.sb?.auth.signOut());
    E.togglePassword.addEventListener('click',()=>{const show=E.loginPassword.type==='password';E.loginPassword.type=show?'text':'password';E.togglePassword.innerHTML=`<i class="bi bi-eye${show?'-slash':''}"></i>`});
    document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.adminTab)));
    E.operatorSearch.addEventListener('input',renderOperatorGrid); E.operatorCategory.addEventListener('change',renderOperatorGrid); E.operatorSaveButton.addEventListener('click',()=>saveInventory(S.profile?.service_id,'operator'));
    E.adminInventoryService.addEventListener('change',()=>{S.adminService=E.adminInventoryService.value||null;renderAdminInventory()}); E.adminInventorySearch.addEventListener('input',renderAdminGrid); E.adminInventoryCategory.addEventListener('change',renderAdminGrid); E.adminInventorySaveButton.addEventListener('click',()=>saveInventory(S.adminService,'admin'));
    E.appShell.addEventListener('click',appClick); E.appShell.addEventListener('input',stockInput);
    E.refreshAdminButton.addEventListener('click',()=>refresh(true)); E.adminServiceSearch.addEventListener('input',renderDashboard); E.materialsSearch.addEventListener('input',renderMaterials); E.materialsStatusFilter.addEventListener('change',renderMaterials);
    E.addServiceButton.addEventListener('click',()=>openService()); E.serviceForm.addEventListener('submit',saveService); E.addMaterialButton.addEventListener('click',()=>openMaterial()); E.materialForm.addEventListener('submit',saveMaterial); E.materialImageFile.addEventListener('change',previewImage); E.userForm.addEventListener('submit',saveUser);
  }

  async function handleSession(session){
    if(S.busy && S.session?.access_token===session?.access_token) return; S.session=session;
    if(!session){teardown();S.profile=null;S.services=[];S.materials=[];S.stocks=[];S.profiles=[];S.history=[];S.drafts.clear();showAuth();return}
    showLoading();S.busy=true;
    try{
      const {data,error}=await S.sb.from('profiles').select('*').eq('id',session.user.id).single();
      if(error||!data) throw new Error('El usuario no tiene perfil. Ejecutá el esquema SQL y revisá el trigger de perfiles.');
      S.profile=data; await refresh(false); setupRealtime(); showApp();
    }catch(err){console.error(err);await S.sb.auth.signOut();showAuth();showLoginError(err.message)}finally{S.busy=false;E.loadingScreen.classList.add('d-none')}
  }

  async function login(ev){ev.preventDefault();hideLoginError();loginBusy(true);try{const {error}=await S.sb.auth.signInWithPassword({email:E.loginEmail.value.trim(),password:E.loginPassword.value});if(error)throw error}catch(err){showLoginError(authMsg(err))}finally{loginBusy(false)}}
  function authMsg(e){const m=String(e?.message||'').toLowerCase();if(m.includes('invalid login credentials'))return'Correo o contraseña incorrectos.';if(m.includes('email not confirmed'))return'El correo todavía no fue confirmado.';return e?.message||'No se pudo iniciar sesión.'}
  function loginBusy(v){E.loginButton.disabled=v;E.loginButton.querySelector('.login-label').classList.toggle('d-none',v);E.loginButton.querySelector('.login-spinner').classList.toggle('d-none',!v)}
  function showLoginError(m){E.loginError.textContent=m;E.loginError.classList.remove('d-none')} function hideLoginError(){E.loginError.classList.add('d-none');E.loginError.textContent=''}
  function showLoading(){E.loadingScreen.classList.remove('d-none')} function showAuth(){E.loadingScreen.classList.add('d-none');E.appShell.classList.add('d-none');E.authView.classList.remove('d-none')}
  function showApp(){E.authView.classList.add('d-none');E.appShell.classList.remove('d-none');E.headerUserName.textContent=S.profile.full_name||S.profile.email||'Usuario';E.headerUserRole.textContent=S.profile.role==='admin'?'Administrador':'Operario';E.appSubtitle.textContent=S.profile.role==='admin'?'Administración de inventario':'Relevamiento de servicio';const a=S.profile.role==='admin';E.adminView.classList.toggle('d-none',!a);E.operatorView.classList.toggle('d-none',a);E.adminMenuButton.classList.toggle('d-none',!a);a?renderAdmin():renderOperator()}

  async function refresh(feedback=false){
    if(!S.profile)return; if(feedback)buttonBusy(E.refreshAdminButton,true,'Actualizando...');
    try{
      const [sv,ma,st]=await Promise.all([S.sb.from('services').select('*').order('name'),S.sb.from('materials').select('*').order('category').order('sort_order').order('name'),S.sb.from('service_stock').select('*').order('updated_at',{ascending:false})]);
      [sv,ma,st].forEach(r=>{if(r.error)throw r.error}); S.services=sv.data||[];S.materials=ma.data||[];S.stocks=st.data||[];
      if(S.profile.role==='admin'){
        const [pr,hi]=await Promise.all([S.sb.from('profiles').select('*').order('full_name'),S.sb.from('stock_history').select('*').order('changed_at',{ascending:false}).limit(250)]);if(pr.error)throw pr.error;if(hi.error)throw hi.error;S.profiles=pr.data||[];S.history=hi.data||[];
        if(!S.adminService||!S.services.some(x=>x.id===S.adminService))S.adminService=S.services.find(x=>x.active)?.id||S.services[0]?.id||null;
      }
      categories(); if(!E.appShell.classList.contains('d-none'))S.profile.role==='admin'?renderAdmin():renderOperator(); if(feedback)toast('Datos actualizados.','success');
    }catch(err){console.error(err);toast(err.message||'No se pudieron actualizar los datos.','error')}finally{if(feedback)buttonBusy(E.refreshAdminButton,false)}
  }
  function setupRealtime(){teardown();S.channel=S.sb.channel(`stock-${S.profile.id}`).on('postgres_changes',{event:'*',schema:'public',table:'service_stock'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'materials'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'services'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'profiles'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'stock_history'},schedule).subscribe()}
  function teardown(){if(S.channel&&S.sb)S.sb.removeChannel(S.channel);S.channel=null} function schedule(){clearTimeout(S.timer);S.timer=setTimeout(()=>refresh(false),450)}
  function categories(){const cats=[...new Set(S.materials.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));[E.operatorCategory,E.adminInventoryCategory].forEach(sel=>{const cur=sel.value;sel.innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option value="${ea(c)}">${eh(c)}</option>`).join('');sel.value=cats.includes(cur)?cur:'all'});E.categorySuggestions.innerHTML=cats.map(c=>`<option value="${ea(c)}"></option>`).join('')}

  function renderOperator(){const s=service(S.profile.service_id),ok=!!s;E.operatorNoService.classList.toggle('d-none',ok);E.operatorContent.classList.toggle('d-none',!ok);E.operatorSaveBar.classList.toggle('d-none',!ok);if(!s)return;const z=summary(s.id);E.operatorServiceName.textContent=s.name;E.operatorServiceAddress.textContent=s.address||'Dirección no informada';E.operatorLastUpdate.textContent=z.last?relative(z.last):'Sin informar';E.operatorCriticalCount.textContent=z.critical;E.operatorLowCount.textContent=z.low;E.operatorOkCount.textContent=z.ok;E.operatorUnreportedCount.textContent=z.unreported;renderOperatorGrid();draftIndicator()}
  function renderOperatorGrid(){if(!S.profile?.service_id)return;renderGrid(E.operatorInventoryGrid,S.profile.service_id,E.operatorSearch.value,E.operatorCategory.value,'operator')}
  function renderAdmin(){renderDashboard();renderAdminInventory();renderMaterials();renderServices();renderUsers();renderHistory();switchTab(S.tab,false)}
  function switchTab(t,set=true){if(set)S.tab=t;document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('d-none',p.dataset.panel!==t));document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===t))}

  function renderDashboard(){if(S.profile?.role!=='admin')return;const act=S.services.filter(x=>x.active),sum=act.map(s=>({s,z:summary(s.id)}));E.adminKpiServices.textContent=act.length;E.adminKpiCritical.textContent=sum.reduce((a,x)=>a+x.z.critical,0);E.adminKpiStale.textContent=sum.filter(x=>x.z.stale).length;E.adminKpiMaterials.textContent=activeMaterials().length;const q=norm(E.adminServiceSearch.value);sum.sort((a,b)=>risk(b.z)-risk(a.z)||a.s.name.localeCompare(b.s.name,'es'));const v=sum.filter(x=>norm(`${x.s.name} ${x.s.address||''}`).includes(q));E.serviceHealthList.innerHTML=v.length?v.map(({s,z})=>`<button class="service-health-item text-start" data-open-service-inventory="${s.id}"><div><div class="service-health-name">${eh(s.name)}</div><div class="service-health-meta">${z.last?`Actualizado ${eh(relative(z.last))}`:'Nunca relevado'}${s.address?` · ${eh(s.address)}`:''}</div></div><div class="health-pills">${z.critical?`<span class="health-pill bg-danger-subtle text-danger">${z.critical} críticos</span>`:''}${z.low?`<span class="health-pill bg-warning-subtle text-warning-emphasis">${z.low} bajos</span>`:''}${z.unreported?`<span class="health-pill bg-secondary-subtle text-secondary">${z.unreported} sin informar</span>`:''}${!z.critical&&!z.low&&!z.unreported?'<span class="health-pill bg-success-subtle text-success">Completo</span>':''}</div></button>`).join(''):empty('No hay servicios que coincidan.');
    const alerts=[];act.forEach(s=>activeMaterials().forEach(m=>{const st=stock(s.id,m.id);if(!st)return;const status=stockStatus(st.quantity,m);if(status==='critical'||status==='low')alerts.push({s,m,st,status})}));alerts.sort((a,b)=>(a.status==='critical'?-1:1)-(b.status==='critical'?-1:1)||a.st.quantity-b.st.quantity);E.priorityAlertCount.textContent=alerts.length;E.priorityAlertsList.innerHTML=alerts.length?alerts.slice(0,18).map(a=>`<button class="priority-item ${a.status==='low'?'low':''} text-start border-0 w-100" data-open-service-inventory="${a.s.id}"><div class="priority-item-title">${eh(a.m.name)} · ${qty(a.st.quantity)}</div><div class="priority-item-meta">${eh(a.s.name)} · crítico ≤ ${qty(a.m.critical_level)} · objetivo ${qty(a.m.target_level)}</div></button>`).join(''):empty('No hay alertas de stock informadas.','bi-check-circle')
  }
  function risk(z){return z.critical*100+z.low*10+z.unreported+(z.stale?50:0)}
  function renderAdminInventory(){if(S.profile?.role!=='admin')return;const sv=S.services.filter(x=>x.active);E.adminInventoryService.innerHTML=sv.length?sv.map(s=>`<option value="${s.id}">${eh(s.name)}</option>`).join(''):'<option value="">No hay servicios activos</option>';if(S.adminService&&sv.some(s=>s.id===S.adminService))E.adminInventoryService.value=S.adminService;else{S.adminService=sv[0]?.id||null;E.adminInventoryService.value=S.adminService||''}const s=service(S.adminService),z=s?summary(s.id):null;E.adminInventorySummary.innerHTML=s?`<strong>${eh(s.name)}</strong> · ${z.last?`Última actualización: ${eh(fmt(z.last))}`:'Sin relevamiento'} · <span class="text-danger fw-bold">${z.critical} críticos</span> · <span class="text-warning-emphasis fw-bold">${z.low} bajos</span> · ${z.unreported} sin informar`:'Creá un servicio para comenzar.';renderAdminGrid()}
  function renderAdminGrid(){renderGrid(E.adminInventoryGrid,S.adminService,E.adminInventorySearch.value,E.adminInventoryCategory.value,'admin');E.adminInventorySaveButton.disabled=!S.adminService}

  function renderGrid(container,serviceId,searchText,category,context){if(!serviceId){container.innerHTML=empty('No hay un servicio seleccionado.');return}const q=norm(searchText);const mats=activeMaterials().filter(m=>(category==='all'||m.category===category)&&(!q||norm(`${m.name} ${m.detail||''} ${m.category}`).includes(q)));container.dataset.serviceId=serviceId;container.innerHTML=mats.length?mats.map(m=>card(serviceId,m,context)).join(''):empty('No hay insumos que coincidan con el filtro.')}
  function card(serviceId,m,context){const st=stock(serviceId,m.id),d=draft(serviceId,m.id),reported=!!st||d!==undefined,value=d!==undefined?d:(st?.quantity??0),status=reported?stockStatus(value,m):'unreported',label={unreported:'Sin informar',critical:'Crítico',low:'Bajo',ok:'Correcto'}[status],img=m.image_url||'assets/materials/default.svg';return `<article class="material-card status-${status}" data-material-card="${m.id}" data-service-id="${serviceId}" data-context="${context}"><div class="material-image-wrap"><img class="material-image" src="${ea(img)}" alt="${ea(m.name)}" loading="lazy" onerror="this.src='assets/materials/default.svg'"><span class="material-status ${status}" data-status-label>${label}</span></div><div class="material-body"><div class="material-category">${eh(m.category)}</div><div class="material-name">${eh(m.name)}</div><div class="material-detail">${eh(m.detail||m.unit)}</div><div class="stock-control"><button class="btn btn-outline-secondary" type="button" data-stock-step="-1"><i class="bi bi-dash"></i></button><input class="form-control stock-input" type="number" min="0" step="0.01" value="${ea(inputQty(value))}" data-stock-input data-material-id="${m.id}" data-service-id="${serviceId}" inputmode="decimal"><button class="btn btn-outline-primary" type="button" data-stock-step="1"><i class="bi bi-plus"></i></button></div><div class="stock-unit">${eh(m.unit)}</div><div class="threshold-note">Crítico ≤ ${qty(m.critical_level)} · objetivo ${qty(m.target_level)}</div></div></article>`}

  function appClick(ev){const step=ev.target.closest('[data-stock-step]');if(step){const c=step.closest('[data-material-card]'),i=c?.querySelector('[data-stock-input]');if(!c||!i)return;const n=Math.max(0,parseQty(i.value)+Number(step.dataset.stockStep));i.value=inputQty(n);setDraft(c.dataset.serviceId,c.dataset.materialCard,n);updateCard(c,n);draftIndicator();return}const open=ev.target.closest('[data-open-service-inventory]');if(open){S.adminService=open.dataset.openServiceInventory;switchTab('inventory');renderAdminInventory();scrollTo({top:0,behavior:'smooth'});return}const es=ev.target.closest('[data-edit-service]');if(es)return openService(service(es.dataset.editService));const ts=ev.target.closest('[data-toggle-service]');if(ts)return toggleService(ts.dataset.toggleService);const em=ev.target.closest('[data-edit-material]');if(em)return openMaterial(material(em.dataset.editMaterial));const tm=ev.target.closest('[data-toggle-material]');if(tm)return toggleMaterial(tm.dataset.toggleMaterial);const eu=ev.target.closest('[data-edit-user]');if(eu)return openUser(profile(eu.dataset.editUser))}
  function stockInput(ev){const i=ev.target.closest('[data-stock-input]');if(!i)return;const c=i.closest('[data-material-card]'),v=Math.max(0,parseQty(i.value));setDraft(i.dataset.serviceId,i.dataset.materialId,v);updateCard(c,v);draftIndicator()}
  function updateCard(c,v){const m=material(c?.dataset.materialCard);if(!c||!m)return;const s=stockStatus(v,m);c.classList.remove('status-unreported','status-critical','status-low','status-ok');c.classList.add(`status-${s}`);const l=c.querySelector('[data-status-label]');if(l){l.className=`material-status ${s}`;l.textContent={critical:'Crítico',low:'Bajo',ok:'Correcto'}[s]}}
  function setDraft(s,m,v){S.drafts.set(`${s}:${m}`,v)} function draft(s,m){return S.drafts.get(`${s}:${m}`)} function draftIndicator(){const s=S.profile?.role==='admin'?S.adminService:S.profile?.service_id,c=[...S.drafts.keys()].filter(k=>k.startsWith(`${s}:`)).length;E.operatorDraftCount.textContent=`${c} cambio${c===1?'':'s'} pendiente${c===1?'':'s'}`}

  async function saveInventory(serviceId,context){if(!serviceId)return;const b=context==='operator'?E.operatorSaveButton:E.adminInventorySaveButton;buttonBusy(b,true,'Guardando...');try{const rows=activeMaterials().map(m=>{const st=stock(serviceId,m.id),d=draft(serviceId,m.id);return{service_id:serviceId,material_id:m.id,quantity:d!==undefined?d:(st?.quantity??0),notes:st?.notes||null,updated_by:S.session.user.id,updated_at:new Date().toISOString()}});if(!rows.length)throw new Error('No hay insumos activos para guardar.');const {error}=await S.sb.from('service_stock').upsert(rows,{onConflict:'service_id,material_id'});if(error)throw error;[...S.drafts.keys()].forEach(k=>{if(k.startsWith(`${serviceId}:`))S.drafts.delete(k)});await refresh(false);toast('Relevamiento guardado correctamente.','success')}catch(err){console.error(err);toast(err.message||'No se pudo guardar el inventario.','error')}finally{buttonBusy(b,false);draftIndicator()}}

  function renderMaterials(){if(S.profile?.role!=='admin')return;const q=norm(E.materialsSearch.value),f=E.materialsStatusFilter.value,arr=S.materials.filter(m=>(!q||norm(`${m.name} ${m.detail||''} ${m.category}`).includes(q))&&(f==='all'||(f==='active'?m.active:!m.active)));E.materialsTableBody.innerHTML=arr.length?arr.map(m=>`<tr><td><div class="table-material"><img class="table-thumb" src="${ea(m.image_url||'assets/materials/default.svg')}" onerror="this.src='assets/materials/default.svg'"><div><div class="table-title">${eh(m.name)}</div><div class="table-subtitle">${eh(m.detail||'Sin detalle')}</div></div></div></td><td>${eh(m.category)}</td><td>${eh(m.unit)}</td><td>${qty(m.critical_level)}</td><td>${qty(m.target_level)}</td><td>${m.active?'<span class="badge text-bg-success">Activo</span>':'<span class="badge text-bg-secondary">Inactivo</span>'}</td><td class="text-end"><div class="action-group"><button class="btn btn-light" data-edit-material="${m.id}"><i class="bi bi-pencil"></i></button><button class="btn ${m.active?'btn-outline-danger':'btn-outline-success'}" data-toggle-material="${m.id}"><i class="bi bi-${m.active?'archive':'check-lg'}"></i></button></div></td></tr>`).join(''):tableEmpty(7,'No hay insumos que coincidan.')}
  function renderServices(){if(S.profile?.role!=='admin')return;E.servicesTableBody.innerHTML=S.services.length?S.services.map(s=>{const z=summary(s.id),n=S.profiles.filter(p=>p.service_id===s.id).length;return`<tr><td><div class="table-title">${eh(s.name)}</div><div class="table-subtitle">${eh(s.notes||'')}</div></td><td>${eh(s.address||'—')}</td><td>${z.last?eh(relative(z.last)):'<span class="text-danger fw-bold">Nunca</span>'}</td><td>${n}</td><td>${s.active?'<span class="badge text-bg-success">Activo</span>':'<span class="badge text-bg-secondary">Inactivo</span>'}</td><td class="text-end"><div class="action-group"><button class="btn btn-light" data-edit-service="${s.id}"><i class="bi bi-pencil"></i></button><button class="btn ${s.active?'btn-outline-danger':'btn-outline-success'}" data-toggle-service="${s.id}"><i class="bi bi-${s.active?'archive':'check-lg'}"></i></button></div></td></tr>`}).join(''):tableEmpty(6,'Todavía no hay servicios.')}
  function renderUsers(){if(S.profile?.role!=='admin')return;E.usersTableBody.innerHTML=S.profiles.length?S.profiles.map(p=>`<tr><td><div class="table-title">${eh(p.full_name||'Sin nombre')}</div></td><td>${eh(p.email||'—')}</td><td>${p.role==='admin'?'<span class="badge text-bg-primary">Administrador</span>':'<span class="badge text-bg-light border">Operario</span>'}</td><td>${eh(service(p.service_id)?.name||'Sin asignar')}</td><td class="text-end"><button class="btn btn-light btn-sm" data-edit-user="${p.id}"><i class="bi bi-pencil me-1"></i>Editar</button></td></tr>`).join(''):tableEmpty(5,'No hay usuarios disponibles.')}
  function renderHistory(){if(S.profile?.role!=='admin')return;E.historyTableBody.innerHTML=S.history.length?S.history.map(h=>`<tr><td class="text-nowrap">${eh(fmt(h.changed_at))}</td><td>${eh(service(h.service_id)?.name||'Servicio eliminado')}</td><td>${eh(material(h.material_id)?.name||'Insumo eliminado')}</td><td><strong>${h.old_quantity===null?'—':qty(h.old_quantity)} → ${qty(h.new_quantity)}</strong></td><td>${eh(profile(h.changed_by)?.full_name||'Sistema')}</td></tr>`).join(''):tableEmpty(5,'No hay movimientos registrados.')}

  function openService(s=null){E.serviceModalTitle.textContent=s?'Editar servicio':'Nuevo servicio';E.serviceId.value=s?.id||'';E.serviceName.value=s?.name||'';E.serviceAddress.value=s?.address||'';E.serviceNotes.value=s?.notes||'';E.serviceActive.checked=s?.active??true;M.service.show()}
  async function saveService(ev){ev.preventDefault();const id=E.serviceId.value,p={name:E.serviceName.value.trim(),address:E.serviceAddress.value.trim()||null,notes:E.serviceNotes.value.trim()||null,active:E.serviceActive.checked,updated_at:new Date().toISOString()};if(!p.name)return;const r=id?await S.sb.from('services').update(p).eq('id',id):await S.sb.from('services').insert(p);if(r.error)return toast(r.error.message,'error');M.service.hide();await refresh(false);toast('Servicio guardado.','success')}
  async function toggleService(id){const s=service(id);if(!s)return;if(!confirm(`¿Confirmás ${s.active?'desactivar':'activar'} ${s.name}?`))return;const {error}=await S.sb.from('services').update({active:!s.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,'error');await refresh(false);toast(`Servicio ${s.active?'desactivado':'activado'}.`,'success')}

  function openMaterial(m=null){E.materialModalTitle.textContent=m?'Editar insumo':'Nuevo insumo';E.materialId.value=m?.id||'';E.materialName.value=m?.name||'';E.materialCategory.value=m?.category||'';E.materialDetail.value=m?.detail||'';E.materialUnit.value=m?.unit||'unidad';E.materialCritical.value=m?.critical_level??0;E.materialTarget.value=m?.target_level??1;E.materialSort.value=m?.sort_order??100;E.materialActive.checked=m?.active??true;E.materialImageFile.value='';E.materialImagePreview.src=m?.image_url||'assets/materials/default.svg';E.materialImagePreview.dataset.currentUrl=m?.image_url||'';M.material.show()}
  function previewImage(){const f=E.materialImageFile.files?.[0];if(!f)return;const u=URL.createObjectURL(f);E.materialImagePreview.src=u;E.materialImagePreview.onload=()=>URL.revokeObjectURL(u)}
  async function uploadImage(file,name){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${Date.now()}-${slug(name||'insumo')}.${ext}`,bucket=cfg.MATERIAL_IMAGE_BUCKET||'material-images';const {error}=await S.sb.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw new Error(`No se pudo subir la imagen: ${error.message}`);return S.sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
  async function saveMaterial(ev){ev.preventDefault();buttonBusy(E.materialSubmitButton,true,'Guardando...');try{const id=E.materialId.value;let image=E.materialImagePreview.dataset.currentUrl||null;const f=E.materialImageFile.files?.[0];if(f)image=await uploadImage(f,E.materialName.value);const p={name:E.materialName.value.trim(),slug:slug(E.materialName.value)+(id?'':`-${Date.now().toString(36)}`),category:E.materialCategory.value.trim(),detail:E.materialDetail.value.trim()||null,unit:E.materialUnit.value.trim(),critical_level:parseQty(E.materialCritical.value),target_level:parseQty(E.materialTarget.value),sort_order:Math.max(0,parseInt(E.materialSort.value||'100',10)),image_url:image,active:E.materialActive.checked,updated_at:new Date().toISOString()};if(!p.name||!p.category||!p.unit)throw new Error('Completá nombre, categoría y unidad.');if(p.target_level<p.critical_level)throw new Error('El stock objetivo no puede ser menor que el nivel crítico.');if(id)delete p.slug;const r=id?await S.sb.from('materials').update(p).eq('id',id):await S.sb.from('materials').insert(p);if(r.error)throw r.error;M.material.hide();await refresh(false);toast('Insumo guardado.','success')}catch(err){toast(err.message||'No se pudo guardar el insumo.','error')}finally{buttonBusy(E.materialSubmitButton,false)}}
  async function toggleMaterial(id){const m=material(id);if(!m)return;if(!confirm(`¿Confirmás ${m.active?'desactivar':'activar'} ${m.name}?`))return;const {error}=await S.sb.from('materials').update({active:!m.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,'error');await refresh(false);toast(`Insumo ${m.active?'desactivado':'activado'}.`,'success')}

  function openUser(p){if(!p)return;E.userId.value=p.id;E.userFullName.value=p.full_name||'';E.userRole.value=p.role||'operator';E.userService.innerHTML='<option value="">Sin asignar</option>'+S.services.filter(s=>s.active).map(s=>`<option value="${s.id}">${eh(s.name)}</option>`).join('');E.userService.value=p.service_id||'';M.user.show()}
  async function saveUser(ev){ev.preventDefault();const p={full_name:E.userFullName.value.trim(),role:E.userRole.value,service_id:E.userService.value||null,updated_at:new Date().toISOString()};if(p.role==='operator'&&!p.service_id)return toast('Un operario debe tener un servicio asignado.','error');const {error}=await S.sb.from('profiles').update(p).eq('id',E.userId.value);if(error)return toast(error.message,'error');M.user.hide();await refresh(false);toast('Usuario actualizado.','success')}

  function activeMaterials(){return S.materials.filter(m=>m.active)} function service(id){return S.services.find(x=>x.id===id)||null} function material(id){return S.materials.find(x=>x.id===id)||null} function profile(id){return S.profiles.find(x=>x.id===id)||(S.profile?.id===id?S.profile:null)} function stock(s,m){return S.stocks.find(x=>x.service_id===s&&x.material_id===m)||null}
  function summary(sid){let critical=0,low=0,ok=0,unreported=0,last=null;activeMaterials().forEach(m=>{const st=stock(sid,m.id);if(!st){unreported++;return}const z=stockStatus(st.quantity,m);if(z==='critical')critical++;if(z==='low')low++;if(z==='ok')ok++;const d=new Date(st.updated_at);if(!last||d>last)last=d});const days=Number(cfg.STOCK_STALE_DAYS||7),stale=!last||(Date.now()-last.getTime())>days*86400000;return{critical,low,ok,unreported,last,stale}}
  function stockStatus(v,m){const n=Number(v)||0,c=Number(m.critical_level)||0,t=Number(m.target_level)||0;return n<=c?'critical':n<t?'low':'ok'}
  function parseQty(v){const n=Number(String(v??0).replace(',','.'));return Number.isFinite(n)?Math.max(0,n):0} function qty(v){return new Intl.NumberFormat('es-AR',{maximumFractionDigits:2}).format(Number(v)||0)} function inputQty(v){const n=Number(v)||0;return Number.isInteger(n)?String(n):String(Math.round(n*100)/100)}
  function fmt(v){if(!v)return'—';const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?'—':dtf.format(d)} function relative(v){const d=v instanceof Date?v:new Date(v),min=Math.round((Date.now()-d.getTime())/60000);if(min<1)return'recién';if(min<60)return`hace ${min} min`;const h=Math.round(min/60);if(h<24)return`hace ${h} h`;const days=Math.round(h/24);return days<=7?`hace ${days} día${days===1?'':'s'}`:fmt(d)}
  function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()} function slug(v){return norm(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'insumo'}
  function buttonBusy(b,v,label='Procesando...'){if(!b)return;if(v){b.dataset.original=b.innerHTML;b.disabled=true;b.innerHTML=`<span class="spinner-border spinner-border-sm me-2"></span>${eh(label)}`}else{b.disabled=false;if(b.dataset.original)b.innerHTML=b.dataset.original;delete b.dataset.original}}
  function toast(m,type='info'){E.appToast.classList.remove('toast-success','toast-error','toast-info');E.appToast.classList.add(`toast-${type}`);E.toastBody.textContent=m;M.toast.show()} function empty(m,icon='bi-inbox'){return`<div class="text-center text-secondary py-5 w-100"><i class="bi ${icon} fs-2 d-block mb-2"></i>${eh(m)}</div>`} function tableEmpty(c,m){return`<tr><td colspan="${c}" class="text-center text-secondary py-5">${eh(m)}</td></tr>`}
  function eh(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function ea(v){return eh(v)}
})();
