-- Stock Clean It · esquema Supabase
-- Ejecutar completo en Supabase > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.services(
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  address text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materials(
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  category text not null,
  detail text,
  unit text not null default 'unidad',
  image_url text,
  critical_level numeric(12,2) not null default 0 check(critical_level>=0),
  target_level numeric(12,2) not null default 1 check(target_level>=critical_level),
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'operator' check(role in('admin','operator')),
  service_id uuid references public.services(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_stock(
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  quantity numeric(12,2) not null default 0 check(quantity>=0),
  notes text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(service_id,material_id)
);

create table if not exists public.stock_history(
  id bigint generated by default as identity primary key,
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  old_quantity numeric(12,2),
  new_quantity numeric(12,2) not null,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists idx_profiles_service on public.profiles(service_id);
create index if not exists idx_stock_service on public.service_stock(service_id);
create index if not exists idx_stock_updated on public.service_stock(updated_at desc);
create index if not exists idx_history_changed on public.stock_history(changed_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
drop trigger if exists materials_set_updated_at on public.materials;
create trigger materials_set_updated_at before update on public.materials for each row execute function public.set_updated_at();
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'operator')
  on conflict(id) do update set email=excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users for each row execute function public.handle_new_user();

insert into public.profiles(id,email,full_name,role)
select id,email,coalesce(raw_user_meta_data->>'full_name',split_part(email,'@',1)),'operator' from auth.users
on conflict(id) do update set email=excluded.email;

create or replace function public.current_profile_service_id() returns uuid language sql stable security definer set search_path=public as $$
  select service_id from public.profiles where id=auth.uid();
$$;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

create or replace function public.audit_stock_change() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    insert into public.stock_history(service_id,material_id,old_quantity,new_quantity,changed_by)
    values(new.service_id,new.material_id,null,new.quantity,coalesce(new.updated_by,auth.uid()));
  elsif old.quantity is distinct from new.quantity then
    insert into public.stock_history(service_id,material_id,old_quantity,new_quantity,changed_by)
    values(new.service_id,new.material_id,old.quantity,new.quantity,coalesce(new.updated_by,auth.uid()));
  end if;
  return new;
end; $$;

drop trigger if exists service_stock_audit on public.service_stock;
create trigger service_stock_audit after insert or update on public.service_stock for each row execute function public.audit_stock_change();

alter table public.services enable row level security;
alter table public.materials enable row level security;
alter table public.profiles enable row level security;
alter table public.service_stock enable row level security;
alter table public.stock_history enable row level security;

drop policy if exists services_read_authenticated on public.services;
drop policy if exists services_admin_insert on public.services;
drop policy if exists services_admin_update on public.services;
drop policy if exists services_admin_delete on public.services;
drop policy if exists materials_read_authenticated on public.materials;
drop policy if exists materials_admin_insert on public.materials;
drop policy if exists materials_admin_update on public.materials;
drop policy if exists materials_admin_delete on public.materials;
drop policy if exists profiles_read_self_or_admin on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists stock_read_scope on public.service_stock;
drop policy if exists stock_insert_scope on public.service_stock;
drop policy if exists stock_update_scope on public.service_stock;
drop policy if exists history_read_scope on public.stock_history;

create policy services_read_authenticated on public.services for select to authenticated using(true);
create policy services_admin_insert on public.services for insert to authenticated with check(public.is_admin());
create policy services_admin_update on public.services for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy services_admin_delete on public.services for delete to authenticated using(public.is_admin());
create policy materials_read_authenticated on public.materials for select to authenticated using(true);
create policy materials_admin_insert on public.materials for insert to authenticated with check(public.is_admin());
create policy materials_admin_update on public.materials for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy materials_admin_delete on public.materials for delete to authenticated using(public.is_admin());
create policy profiles_read_self_or_admin on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_admin_update on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy stock_read_scope on public.service_stock for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());
create policy stock_insert_scope on public.service_stock for insert to authenticated with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy stock_update_scope on public.service_stock for update to authenticated using(public.is_admin() or service_id=public.current_profile_service_id()) with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy history_read_scope on public.stock_history for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());

insert into storage.buckets(id,name,public) values('material-images','material-images',true)
on conflict(id) do update set public=true;
drop policy if exists material_images_public_read on storage.objects;
drop policy if exists material_images_admin_insert on storage.objects;
drop policy if exists material_images_admin_update on storage.objects;
drop policy if exists material_images_admin_delete on storage.objects;
create policy material_images_public_read on storage.objects for select using(bucket_id='material-images');
create policy material_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_update on storage.objects for update to authenticated using(bucket_id='material-images' and public.is_admin()) with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='material-images' and public.is_admin());

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='service_stock') then alter publication supabase_realtime add table public.service_stock; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='materials') then alter publication supabase_realtime add table public.materials; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='services') then alter publication supabase_realtime add table public.services; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='profiles') then alter publication supabase_realtime add table public.profiles; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='stock_history') then alter publication supabase_realtime add table public.stock_history; end if;
end $$;

insert into public.services(name,address,notes,active) values('Consorcio Demo','Editar desde Administración','Servicio inicial para validar la instalación.',true)
on conflict(name) do nothing;

insert into public.materials(slug,name,category,detail,unit,image_url,critical_level,target_level,sort_order,active) values
  ('detergente-bio-ultra','Detergente ultraconcentrado','Químicos','Bio Ultra - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/detergente-bio-ultra.svg',0,1,10,true),
  ('perfume-flower','Perfume o aromatizante de piso','Químicos','Flower - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/perfume-flower.svg',0,1,20,true),
  ('lavandina-bio-lav','Lavandina líquida desinfectante','Químicos','Bio Lav - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/lavandina-bio-lav.svg',0,1,30,true),
  ('rapid-plus-gel','Lavandina en gel desinfectante','Químicos','Rapid Plus en gel - Thames · 500 ml','envase x 500 ml','assets/materials/rapid-plus-gel.svg',0,1,40,true),
  ('wood-thames','Wood','Químicos','Thames · 360 cm3','envase x 360 cm3','assets/materials/wood-thames.svg',0,1,50,true),
  ('steel-shine','Steel Shine','Químicos','Thames · 390 cm3','aerosol x 390 cm3','assets/materials/steel-shine.svg',0,1,60,true),
  ('cream-thames','Cream','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/cream-thames.svg',0,1,70,true),
  ('sarro-attack','Sarro Attack','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/sarro-attack.svg',0,1,80,true),
  ('smell-thames','Smell o aromatizante ambiental','Químicos','Thames · 262 ml','envase x 262 ml','assets/materials/smell-thames.svg',1,3,90,true),
  ('alcohol-al70','Alcohol AL70','Químicos','Thames · bidón x 5 Lts · sugerido para gimnasio','bidón x 5 Lts','assets/materials/alcohol-al70.svg',0,1,100,true),
  ('bolsas-negras-45-60','Bolsas negras 45x60','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-45-60.svg',0,1,110,true),
  ('bolsas-verdes-45-60','Bolsas verdes 45x60','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-45-60.svg',0,1,120,true),
  ('bolsas-negras-70-50','Bolsas negras 70x50','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-70-50.svg',0,1,130,true),
  ('bolsas-verdes-70-50','Bolsas verdes 70x50','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-70-50.svg',0,1,140,true),
  ('bolsas-negras-90-110','Bolsas negras 90x110','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-90-110.svg',0,1,150,true),
  ('bolsas-verdes-90-110','Bolsas verdes 90x110','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-90-110.svg',0,1,160,true),
  ('guantes-mapa-8','Guantes Mapa Talle 8','Elementos','Par de guantes','par','assets/materials/guantes-mapa-8.svg',0,1,170,true),
  ('balde-reforzado','Balde reforzado','Elementos','10 Lts','unidad','assets/materials/balde-reforzado.svg',0,1,180,true),
  ('pulverizador-gatillo','Pulverizador de 1 Lt + Gatillo','Elementos','Botella pulverizadora completa','unidad','assets/materials/pulverizador-gatillo.svg',0,2,190,true),
  ('medidor','Medidor','Elementos','Para dosificación de productos','unidad','assets/materials/medidor.svg',0,1,200,true),
  ('embudo-mediano','Embudo mediano','Elementos','Para trasvase controlado','unidad','assets/materials/embudo-mediano.svg',0,1,210,true),
  ('escoba-cabo','Escoba + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/escoba-cabo.svg',0,2,220,true),
  ('escobillon-cochera','Escobillón largo base madera + Cabo metálico','Utensilios','Para servicios con cochera','unidad','assets/materials/escobillon-cochera.svg',0,1,230,true),
  ('pala-cabo','Pala + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/pala-cabo.svg',0,1,240,true),
  ('secador-cabo','Secador + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/secador-cabo.svg',0,1,250,true),
  ('trapo-piso','Trapo de piso','Paños y fibras','Uso operativo general','unidad','assets/materials/trapo-piso.svg',0,2,260,true),
  ('rejilla','Rejilla','Paños y fibras','Uso operativo general','unidad','assets/materials/rejilla.svg',0,2,270,true),
  ('microfibra','Microfibra','Paños y fibras','Uso operativo general','unidad','assets/materials/microfibra.svg',0,2,280,true),
  ('fibra-verde','Fibra verde','Paños y fibras','Uso operativo general','unidad','assets/materials/fibra-verde.svg',0,2,290,true),
  ('esponja-acero','Esponja acero inoxidable','Paños y fibras','Uso operativo específico','unidad','assets/materials/esponja-acero.svg',0,2,300,true),
  ('esponja-amarilla','Esponja amarilla','Paños y fibras','Uso operativo general','unidad','assets/materials/esponja-amarilla.svg',0,2,310,true),
  ('plumero-microfibra','Plumero microfibra','Utensilios','Para superficies y altura baja','unidad','assets/materials/plumero-microfibra.svg',0,1,320,true),
  ('ballerina','Ballerina','Paños y fibras','Uso operativo general','unidad','assets/materials/ballerina.svg',0,2,330,true),
  ('kit-vidrios','Corderito + Secador + Agarre secador','Vidrios y altura','Kit para limpieza de vidrios','kit','assets/materials/kit-vidrios.svg',0,1,340,true),
  ('globo-telaranas','Globo para telarañas + cabo telescópico','Vidrios y altura','Cabo telescópico 2 + 2 metros','unidad','assets/materials/globo-telaranas.svg',0,1,350,true)
on conflict(slug) do update set
  name=excluded.name,category=excluded.category,detail=excluded.detail,unit=excluded.unit,
  image_url=coalesce(public.materials.image_url,excluded.image_url),sort_order=excluded.sort_order;

-- Después de crear tu usuario en Authentication, promoverlo a administrador:
-- update public.profiles set role='admin',full_name='Administrador Clean It' where email='TU-CORREO@DOMINIO.COM';
