-- Stock Clean It · esquema Supabase v5
-- Ejecutar completo en Supabase > SQL Editor.
-- Es idempotente: también actualiza una instalación de la versión anterior.
create extension if not exists pgcrypto;

create table if not exists public.services(
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  address text,
  description text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.services add column if not exists description text;

create table if not exists public.materials(
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  category text not null,
  detail text,
  unit text not null default 'unidad',
  control_type text not null default 'integer' check(control_type in('integer','fractional','quantity_condition')),
  image_url text,
  critical_level numeric(12,2) not null default 0 check(critical_level>=0),
  target_level numeric(12,2) not null default 1 check(target_level>=critical_level),
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.materials add column if not exists control_type text not null default 'integer';
alter table public.materials drop constraint if exists materials_control_type_check;
alter table public.materials add constraint materials_control_type_check check(control_type in('integer','fractional','quantity_condition'));

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'operator' check(role in('admin','operator')),
  service_id uuid references public.services(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_stock(
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  quantity numeric(12,2) not null default 0 check(quantity>=0),
  condition_status text check(condition_status is null or condition_status in('good','used','replace')),
  notes text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(service_id,material_id)
);


-- Configuración por excepción: si no existe una fila, el insumo está visible.
create table if not exists public.service_material_visibility(
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  enabled boolean not null default true,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key(service_id,material_id)
);

alter table public.service_stock add column if not exists condition_status text;
alter table public.service_stock drop constraint if exists service_stock_condition_status_check;
alter table public.service_stock add constraint service_stock_condition_status_check check(condition_status is null or condition_status in('good','used','replace'));

create table if not exists public.stock_history(
  id bigint generated by default as identity primary key,
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  old_quantity numeric(12,2),
  new_quantity numeric(12,2) not null,
  old_condition text,
  new_condition text,
  changed_by uuid references public.profiles(id) on delete set null,
  reporter_name text,
  changed_at timestamptz not null default now()
);

alter table public.stock_history add column if not exists reporter_name text;
alter table public.stock_history add column if not exists old_condition text;
alter table public.stock_history add column if not exists new_condition text;

create table if not exists public.service_extra_stock(
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  name text not null check(char_length(btrim(name)) between 2 and 120),
  unit text not null default 'unidad',
  quantity numeric(12,2) not null default 0 check(quantity>=0),
  notes text,
  image_url text,
  critical_level numeric(12,2) not null default 0 check(critical_level>=0),
  target_level numeric(12,2) not null default 1 check(target_level>=critical_level),
  submitted_by text,
  updated_by uuid references public.profiles(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.extra_stock_history(
  id bigint generated by default as identity primary key,
  extra_stock_id uuid references public.service_extra_stock(id) on delete set null,
  service_id uuid not null references public.services(id) on delete cascade,
  extra_name text not null,
  old_quantity numeric(12,2),
  new_quantity numeric(12,2) not null,
  changed_by uuid references public.profiles(id) on delete set null,
  reporter_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_profiles_service on public.profiles(service_id);
create index if not exists idx_stock_service on public.service_stock(service_id);
create index if not exists idx_stock_updated on public.service_stock(updated_at desc);
create index if not exists idx_visibility_service on public.service_material_visibility(service_id);
create index if not exists idx_visibility_material on public.service_material_visibility(material_id);
create index if not exists idx_history_changed on public.stock_history(changed_at desc);
create index if not exists idx_extra_service on public.service_extra_stock(service_id);
create index if not exists idx_extra_updated on public.service_extra_stock(updated_at desc);
create index if not exists idx_extra_history_changed on public.extra_stock_history(changed_at desc);
create unique index if not exists idx_extra_unique_service_name on public.service_extra_stock(service_id, lower(btrim(name)));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
drop trigger if exists materials_set_updated_at on public.materials;
create trigger materials_set_updated_at before update on public.materials for each row execute function public.set_updated_at();
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists extra_stock_set_updated_at on public.service_extra_stock;
create trigger extra_stock_set_updated_at before update on public.service_extra_stock for each row execute function public.set_updated_at();
drop trigger if exists service_material_visibility_set_updated_at on public.service_material_visibility;
create trigger service_material_visibility_set_updated_at before update on public.service_material_visibility for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'operator')
  on conflict(id) do update set email=excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users for each row execute function public.handle_new_user();

insert into public.profiles(id,email,full_name,role)
select id,email,coalesce(raw_user_meta_data->>'full_name',split_part(email,'@',1)),'operator' from auth.users
on conflict(id) do update set email=excluded.email;

create or replace function public.current_profile_service_id() returns uuid language sql stable security definer set search_path=public as $$
  select service_id from public.profiles where id=auth.uid();
$$;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

create or replace function public.audit_stock_change() returns trigger language plpgsql security definer set search_path=public as $$
declare
  v_reporter text := nullif(current_setting('app.reporter_name',true),'');
begin
  if tg_op='INSERT' then
    insert into public.stock_history(service_id,material_id,old_quantity,new_quantity,old_condition,new_condition,changed_by,reporter_name)
    values(new.service_id,new.material_id,null,new.quantity,null,new.condition_status,coalesce(new.updated_by,auth.uid()),v_reporter);
  elsif old.quantity is distinct from new.quantity or old.condition_status is distinct from new.condition_status then
    insert into public.stock_history(service_id,material_id,old_quantity,new_quantity,old_condition,new_condition,changed_by,reporter_name)
    values(new.service_id,new.material_id,old.quantity,new.quantity,old.condition_status,new.condition_status,coalesce(new.updated_by,auth.uid()),v_reporter);
  end if;
  return new;
end; $$;

drop trigger if exists service_stock_audit on public.service_stock;
create trigger service_stock_audit after insert or update on public.service_stock for each row execute function public.audit_stock_change();

create or replace function public.audit_extra_stock_change() returns trigger language plpgsql security definer set search_path=public as $$
declare
  v_reporter text;
begin
  v_reporter := coalesce(nullif(current_setting('app.reporter_name',true),''),new.submitted_by);
  if tg_op='INSERT' then
    insert into public.extra_stock_history(extra_stock_id,service_id,extra_name,old_quantity,new_quantity,changed_by,reporter_name)
    values(new.id,new.service_id,new.name,null,new.quantity,coalesce(new.updated_by,auth.uid()),v_reporter);
  elsif old.quantity is distinct from new.quantity then
    insert into public.extra_stock_history(extra_stock_id,service_id,extra_name,old_quantity,new_quantity,changed_by,reporter_name)
    values(new.id,new.service_id,new.name,old.quantity,new.quantity,coalesce(new.updated_by,auth.uid()),v_reporter);
  end if;
  return new;
end; $$;

drop trigger if exists service_extra_stock_audit on public.service_extra_stock;
create trigger service_extra_stock_audit after insert or update on public.service_extra_stock for each row execute function public.audit_extra_stock_change();

alter table public.services enable row level security;
alter table public.materials enable row level security;
alter table public.profiles enable row level security;
alter table public.service_stock enable row level security;
alter table public.service_material_visibility enable row level security;

grant select,insert,update,delete on table public.service_material_visibility to authenticated;
alter table public.stock_history enable row level security;
alter table public.service_extra_stock enable row level security;
alter table public.extra_stock_history enable row level security;

drop policy if exists services_read_authenticated on public.services;
drop policy if exists services_admin_insert on public.services;
drop policy if exists services_admin_update on public.services;
drop policy if exists services_admin_delete on public.services;
drop policy if exists materials_read_authenticated on public.materials;
drop policy if exists materials_admin_insert on public.materials;
drop policy if exists materials_admin_update on public.materials;
drop policy if exists materials_admin_delete on public.materials;
drop policy if exists profiles_read_self_or_admin on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists stock_read_scope on public.service_stock;
drop policy if exists stock_insert_scope on public.service_stock;
drop policy if exists stock_update_scope on public.service_stock;
drop policy if exists visibility_read_scope on public.service_material_visibility;
drop policy if exists visibility_admin_insert on public.service_material_visibility;
drop policy if exists visibility_admin_update on public.service_material_visibility;
drop policy if exists visibility_admin_delete on public.service_material_visibility;
drop policy if exists history_read_scope on public.stock_history;
drop policy if exists extra_stock_read_scope on public.service_extra_stock;
drop policy if exists extra_stock_insert_scope on public.service_extra_stock;
drop policy if exists extra_stock_update_scope on public.service_extra_stock;
drop policy if exists extra_stock_delete_admin on public.service_extra_stock;
drop policy if exists extra_history_read_scope on public.extra_stock_history;

create policy services_read_authenticated on public.services for select to authenticated using(true);
create policy services_admin_insert on public.services for insert to authenticated with check(public.is_admin());
create policy services_admin_update on public.services for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy services_admin_delete on public.services for delete to authenticated using(public.is_admin());
create policy materials_read_authenticated on public.materials for select to authenticated using(true);
create policy materials_admin_insert on public.materials for insert to authenticated with check(public.is_admin());
create policy materials_admin_update on public.materials for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy materials_admin_delete on public.materials for delete to authenticated using(public.is_admin());
create policy profiles_read_self_or_admin on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_admin_update on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy stock_read_scope on public.service_stock for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());
create policy stock_insert_scope on public.service_stock for insert to authenticated with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy stock_update_scope on public.service_stock for update to authenticated using(public.is_admin() or service_id=public.current_profile_service_id()) with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy visibility_read_scope on public.service_material_visibility for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());
create policy visibility_admin_insert on public.service_material_visibility for insert to authenticated with check(public.is_admin());
create policy visibility_admin_update on public.service_material_visibility for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy visibility_admin_delete on public.service_material_visibility for delete to authenticated using(public.is_admin());
create policy history_read_scope on public.stock_history for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());
create policy extra_stock_read_scope on public.service_extra_stock for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());
create policy extra_stock_insert_scope on public.service_extra_stock for insert to authenticated with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy extra_stock_update_scope on public.service_extra_stock for update to authenticated using(public.is_admin() or service_id=public.current_profile_service_id()) with check(public.is_admin() or service_id=public.current_profile_service_id());
create policy extra_stock_delete_admin on public.service_extra_stock for delete to authenticated using(public.is_admin());
create policy extra_history_read_scope on public.extra_stock_history for select to authenticated using(public.is_admin() or service_id=public.current_profile_service_id());

-- Lectura pública controlada. No expone perfiles, historial ni notas internas de servicios.
create or replace function public.public_inventory_bootstrap(p_service_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_services jsonb;
  v_materials jsonb;
  v_stocks jsonb := '[]'::jsonb;
  v_extras jsonb := '[]'::jsonb;
begin
  if p_service_id is not null and not exists(
    select 1 from public.services where id=p_service_id and active=true
  ) then
    raise exception 'El servicio seleccionado no existe o está inactivo.';
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.name),'[]'::jsonb)
  into v_services
  from (
    select id,name,address,description,active
    from public.services
    where active=true
  ) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.category,x.sort_order,x.name),'[]'::jsonb)
  into v_materials
  from (
    select m.id,m.slug,m.name,m.category,m.detail,m.unit,m.control_type,m.image_url,m.critical_level,m.target_level,m.sort_order,m.active
    from public.materials m
    where m.active=true
      and (
        p_service_id is null
        or not exists(
          select 1
          from public.service_material_visibility smv
          where smv.service_id=p_service_id
            and smv.material_id=m.id
            and smv.enabled=false
        )
      )
  ) x;

  if p_service_id is not null then
    select coalesce(jsonb_agg(to_jsonb(x) order by x.updated_at desc),'[]'::jsonb)
    into v_stocks
    from (
      select ss.id,ss.service_id,ss.material_id,ss.quantity,ss.condition_status,ss.notes,ss.updated_at
      from public.service_stock ss
      join public.materials m on m.id=ss.material_id and m.active=true
      where ss.service_id=p_service_id
        and not exists(
          select 1
          from public.service_material_visibility smv
          where smv.service_id=p_service_id
            and smv.material_id=ss.material_id
            and smv.enabled=false
        )
    ) x;

    select coalesce(jsonb_agg(to_jsonb(x) order by x.name),'[]'::jsonb)
    into v_extras
    from (
      select id,service_id,name,unit,quantity,notes,image_url,critical_level,target_level,submitted_by,active,created_at,updated_at
      from public.service_extra_stock
      where service_id=p_service_id and active=true
    ) x;
  end if;

  return jsonb_build_object(
    'services',v_services,
    'materials',v_materials,
    'stocks',v_stocks,
    'extra_stocks',v_extras
  );
end;
$$;

-- Guarda un relevamiento público sin conceder acceso anónimo directo a las tablas.
create or replace function public.public_submit_inventory(
  p_service_id uuid,
  p_stock_items jsonb,
  p_extra_items jsonb default '[]'::jsonb,
  p_reporter_name text default 'Operario sin identificar'
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_item jsonb;
  v_material_id uuid;
  v_extra_id uuid;
  v_quantity numeric(12,2);
  v_condition text;
  v_control_type text;
  v_reporter text := left(coalesce(nullif(btrim(p_reporter_name),''),'Operario sin identificar'),100);
  v_user uuid;
  v_count integer := 0;
begin
  if not exists(select 1 from public.services where id=p_service_id and active=true) then
    raise exception 'El servicio seleccionado no existe o está inactivo.';
  end if;
  if jsonb_typeof(coalesce(p_stock_items,'[]'::jsonb)) <> 'array' or jsonb_typeof(coalesce(p_extra_items,'[]'::jsonb)) <> 'array' then
    raise exception 'El formato del relevamiento no es válido.';
  end if;
  if jsonb_array_length(coalesce(p_stock_items,'[]'::jsonb)) > 250 or jsonb_array_length(coalesce(p_extra_items,'[]'::jsonb)) > 100 then
    raise exception 'El relevamiento supera la cantidad permitida de registros.';
  end if;

  select id into v_user from public.profiles where id=auth.uid();
  perform set_config('app.reporter_name',v_reporter,true);

  for v_item in select value from jsonb_array_elements(coalesce(p_stock_items,'[]'::jsonb)) loop
    v_material_id := (v_item->>'material_id')::uuid;
    v_quantity := greatest(0,least(999999,coalesce((v_item->>'quantity')::numeric,0)));
    select m.control_type into v_control_type
    from public.materials m
    where m.id=v_material_id
      and m.active=true
      and not exists(
        select 1
        from public.service_material_visibility smv
        where smv.service_id=p_service_id
          and smv.material_id=m.id
          and smv.enabled=false
      );

    if found then
      v_condition := nullif(v_item->>'condition_status','');
      if v_control_type <> 'quantity_condition' or coalesce(v_condition,'') not in('good','used','replace') then
        v_condition := null;
      end if;

      insert into public.service_stock(service_id,material_id,quantity,condition_status,updated_by,updated_at)
      values(p_service_id,v_material_id,v_quantity,v_condition,v_user,now())
      on conflict(service_id,material_id) do update set
        quantity=excluded.quantity,
        condition_status=excluded.condition_status,
        updated_by=excluded.updated_by,
        updated_at=now();
      v_count := v_count + 1;
    end if;
  end loop;

  for v_item in select value from jsonb_array_elements(coalesce(p_extra_items,'[]'::jsonb)) loop
    v_extra_id := (v_item->>'id')::uuid;
    v_quantity := greatest(0,least(999999,coalesce((v_item->>'quantity')::numeric,0)));
    update public.service_extra_stock
    set quantity=v_quantity,submitted_by=v_reporter,updated_by=v_user,updated_at=now()
    where id=v_extra_id and service_id=p_service_id and active=true;
    if found then v_count := v_count + 1; end if;
  end loop;

  return jsonb_build_object('ok',true,'updated_records',v_count,'updated_at',now());
end;
$$;

-- Agrega o actualiza un insumo no catalogado, limitado al servicio elegido.
create or replace function public.public_add_extra_stock(
  p_service_id uuid,
  p_name text,
  p_quantity numeric,
  p_unit text default 'unidad',
  p_notes text default null,
  p_reporter_name text default 'Operario sin identificar'
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_id uuid;
  v_name text := left(btrim(coalesce(p_name,'')),120);
  v_unit text := left(coalesce(nullif(btrim(p_unit),''),'unidad'),60);
  v_notes text := nullif(left(btrim(coalesce(p_notes,'')),180),'');
  v_quantity numeric(12,2) := greatest(0,least(999999,coalesce(p_quantity,0)));
  v_reporter text := left(coalesce(nullif(btrim(p_reporter_name),''),'Operario sin identificar'),100);
  v_user uuid;
  v_result jsonb;
begin
  if not exists(select 1 from public.services where id=p_service_id and active=true) then
    raise exception 'El servicio seleccionado no existe o está inactivo.';
  end if;
  if char_length(v_name) < 2 then raise exception 'Ingresá un nombre válido para el insumo.'; end if;
  if exists(select 1 from public.materials where active=true and lower(btrim(name))=lower(v_name)) then
    raise exception 'Ese insumo ya existe en el catálogo precargado.';
  end if;

  select id into v_user from public.profiles where id=auth.uid();
  perform set_config('app.reporter_name',v_reporter,true);

  select id into v_id
  from public.service_extra_stock
  where service_id=p_service_id and lower(btrim(name))=lower(v_name)
  limit 1;

  if v_id is null then
    insert into public.service_extra_stock(service_id,name,unit,quantity,notes,submitted_by,updated_by,active)
    values(p_service_id,v_name,v_unit,v_quantity,v_notes,v_reporter,v_user,true)
    returning id into v_id;
  else
    update public.service_extra_stock
    set name=v_name,unit=v_unit,quantity=v_quantity,notes=v_notes,submitted_by=v_reporter,updated_by=v_user,active=true,updated_at=now()
    where id=v_id;
  end if;

  select to_jsonb(x) into v_result
  from (
    select id,service_id,name,unit,quantity,notes,image_url,critical_level,target_level,submitted_by,active,created_at,updated_at
    from public.service_extra_stock where id=v_id
  ) x;
  return v_result;
end;
$$;

revoke all on function public.public_inventory_bootstrap(uuid) from public;
revoke all on function public.public_submit_inventory(uuid,jsonb,jsonb,text) from public;
revoke all on function public.public_add_extra_stock(uuid,text,numeric,text,text,text) from public;
grant execute on function public.public_inventory_bootstrap(uuid) to anon,authenticated;
grant execute on function public.public_submit_inventory(uuid,jsonb,jsonb,text) to anon,authenticated;
grant execute on function public.public_add_extra_stock(uuid,text,numeric,text,text,text) to anon,authenticated;

insert into storage.buckets(id,name,public) values('material-images','material-images',true)
on conflict(id) do update set public=true;
drop policy if exists material_images_public_read on storage.objects;
drop policy if exists material_images_admin_insert on storage.objects;
drop policy if exists material_images_admin_update on storage.objects;
drop policy if exists material_images_admin_delete on storage.objects;
create policy material_images_public_read on storage.objects for select using(bucket_id='material-images');
create policy material_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_update on storage.objects for update to authenticated using(bucket_id='material-images' and public.is_admin()) with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='material-images' and public.is_admin());

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='service_stock') then alter publication supabase_realtime add table public.service_stock; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='service_extra_stock') then alter publication supabase_realtime add table public.service_extra_stock; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='service_material_visibility') then alter publication supabase_realtime add table public.service_material_visibility; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='materials') then alter publication supabase_realtime add table public.materials; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='services') then alter publication supabase_realtime add table public.services; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='profiles') then alter publication supabase_realtime add table public.profiles; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='stock_history') then alter publication supabase_realtime add table public.stock_history; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='extra_stock_history') then alter publication supabase_realtime add table public.extra_stock_history; end if;
end $$;

-- Servicios Clean It precargados desde el relevamiento operativo del 23/06/2026.
-- En una reinstalación agrega los servicios faltantes. Si el servicio ya existe,
-- sólo completa campos vacíos para no pisar ediciones hechas desde Administración.
insert into public.services(name,address,description,notes,active) values
  ('Alvarez Thomas 550- Colegiales','Alvarez Thomas 550','Lunes a viernes de 13 a 17 hs. Sábado de 8 a 12 hs.',null,true),
  ('America Tampas- P.Industrial Pilar','Parque industrial, C. 9 1761, B1629 Pilar','Lunes a viernes de 8 a 16 hs. Sábado de 8 a 12 hs.',null,true),
  ('Av De los Incas 3502','Av De los Incas 3502','Lunes, miércoles y viernes de 13 a 17 hs.',null,true),
  ('Av MITRE 5834 - Caseros','Av MITRE 5834 - Caseros','Lunes, miércoles y viernes de 7:30 a 11:30 hs.',null,true),
  ('Av. San Juan 440','Av. San Juan 440','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Callao 441 - Centro','Callao 441 - Centro','Lunes a viernes de 13 a 17 hs.',null,true),
  ('Ceretti 2161 - Villa Urquiza','Ceretti 2161','Lunes a sábados de 8 a 12 hs.',null,true),
  ('Céspedes 2524, CABA','Céspedes 2524 - Adm Holmberg/Cespedes - Fernando','Lunes a viernes de 8 a 12 hs.',null,true),
  ('cons Cabildo 2659','Cabildo 2659','Lunes a viernes de 13 a 16 hs.',null,true),
  ('Cons. Agrelo 3641- Boedo','Agrelo 3641','Lunes, miércoles y viernes de 11:30 a 13:30 hs.',null,true),
  ('Cons. Araujo 61-Villa Luro','Araujo 61','Lunes, miércoles y viernes de 9 a 12 hs.',null,true),
  ('Cons. Av Directorio 1821','Av Directorio 1821','Viernes de 12:30 a 15:30 hs.',null,true),
  ('Cons. Av Los Incas 3501','Av Los Incas 3501','Lunes a sábados de 8 a 12 hs.',null,true),
  ('Cons. Beiro 4545- Villa Devoto','Avenida Beiro 4545','Lunes a sábados de 8:30 a 12:30 hs.','Lunes a sábados 8:30 a 12:30',true),
  ('Cons. Cabildo 2737- Nuñez','Cabildo 2737','Lunes a viernes de 8 a 12 hs.',null,true),
  ('Cons. Cachimayo 748- Parque Chacabuco','Cachimayo 748','Lunes a sábados de 8 a 12 hs.',null,true),
  ('Cons. Catamarca 586- San Cristóbal','Catamarca 586','Lunes, miércoles y viernes de 13 a 16 hs.',null,true),
  ('Cons. Cnel Diaz 1450','Coronel Diaz 1450','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Cons. Darwin 524- Villa Crespo','Darwin 524','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons. Gualeguaychú 1938- Villa Devoto','Gualeguaychú 1938','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons. Gualeguaychú 3809/11 caba','Gualeguaychú 3809','Martes y jueves de 8 a 11 hs.',null,true),
  ('Cons. Guardia Vieja 3919-Villa Crespo','Guardia Vieja 3919','Martes y sábado de 8 a 12 hs.',null,true),
  ('Cons. Hipólito Yrigoyen 3132- Once','Hipólito Yrigoyen 3132','Martes y jueves de 13 a 17 hs. Sábado de 8 a 12 hs.',null,true),
  ('Cons. Jose Hernández 2678- Belgrano','Jose Hernández 2678','Lunes y viernes de 8 a 11 hs.',null,true),
  ('Cons. José Marmol 2134 CABA','José Marmol 2134','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Cons. Juian Álvarez 1340- Villa Crespo','Julian Álvarez 1340','Martes y jueves de 7 a 12 hs. Sábado de 7 a 13 hs.',null,true),
  ('Cons. Juncal 2899','Juncal 2899','Lunes a sábados de 8 a 12 hs.',null,true),
  ('Cons. Lascano 4032','Lascano 4032','Miércoles y sábado de 8 a 12 hs.',null,true),
  ('Cons. Lezica 4475','Lezica 4475','Lunes a sábados de 8 a 12 hs.',null,true),
  ('Cons. Luis M Campos 1027','Luis M Campos 1027','Lunes a viernes de 8 a 14 hs. Sábado de 8 a 12 hs.',null,true),
  ('Cons. Manzanares 1753','Manzanares 1753','Martes, jueves y sábado de 13 a 17 hs.',null,true),
  ('Cons. Migueletes 1762','Migueletes 1762','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons. MIRABILA Humboldt 2045 CABA','Humboldt 2045','Sin cobertura activa informada en el archivo.',null,true),
  ('Cons. Moldes 1648- Nuñez','Moldes 1648','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Cons. Olagüer y Feliu 2970- Colegiales','Olagüer y Feliu 2970','Lunes a sábados de 13 a 16 hs.',null,true),
  ('Cons. Plaza 3547- Coghlan','Plaza 3547','Martes y viernes de 16 a 19 hs.',null,true),
  ('Cons. Puan 256/60- Caballito','Puan 256/60','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons. Rivadavia 9037-Floresta','Rivadavia 9037','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons. Roosevelt 1926- Belgrano','Roosevelt 1926','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Cons.Aristobulo del Valle 1301-La Boca.','Aristobulo del Valle 1301','Lunes a viernes de 8 a 16 hs. Sábado de 8 a 12 hs.',null,true),
  ('Cons.Ciudad de la Paz 575','Ciudad de la Paz 575','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Cons.Palacio Cabrera 5356- Palermo','Cabrera 5356','Lunes a viernes de 8 a 14 hs. Sábado de 8 a 12 hs.',null,true),
  ('Cons.Thomas Le Bretón 5153 - Villa Urquiza','Le Bretón 5153','Martes, jueves y sábado de 8 a 12 hs.',null,true),
  ('Florentino Ameghino 680','Florentino Ameghino 680','Lunes, miércoles y viernes de 12 a 16 hs.',null,true),
  ('Gym Formosa 168- Parque Chacabuco','Formosa 168','Martes y jueves de 13 a 17 hs.',null,true),
  ('Holmberg 4150 - Saavedra','Holmberg 4150','Miércoles y viernes de 13 a 17 hs.',null,true),
  ('ISEM SA','Emilio Mitre 1970','Lunes, miércoles y jueves de 12:30 a 16:30 hs.','DE BAJA',true),
  ('Laboratorio Eurolab -Juan de Garay 3831-Boedo','Juan de Garay 3831','Lunes a viernes de 8 a 11 hs.',null,true),
  ('Ludoplast Caseros LEONISMO ARGENTINO 3264 -CASEROS','LEONISMO ARGENTINO 3264','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Martinez castro 263','Martinez castro 263','Lunes y miércoles de 9 a 12 hs. Viernes de 8 a 12 hs.',null,true),
  ('Molycentro - A- Lamas 2135- V- Crespo','Andres Lamas 2135','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Molysil Avellaneda - Catamarca 1856','Catamarca 1856','Martes y jueves de 12 a 17 hs.',null,true),
  ('Molysil- Olagüer y Feliü 3398 Colegiales','Olagüer y Feliü 3398','Martes y jueves de 7:30 a 11:30 hs.',null,true),
  ('Monteagudo 121 Ramos Mejia','Monteagudo 121 Ramos Mejia - Adrián Palumbo','Lunes a sábados de 13 a 19 hs.',null,true),
  ('mundo chipa','Estrada 1859, villa maipú','Lunes a viernes de 13 a 17 hs.',null,true),
  ('Oficina Av Cordoba 1309','Av Cordoba 1309','Lunes, miércoles y viernes de 14 a 18 hs. Martes y jueves de 16 a 18 hs.',null,true),
  ('Oficina Naon Casa Central','Naon 3475','Lunes, miércoles y viernes de 12:30 a 16:30 hs.',null,true),
  ('Pergamino 160','Pergamino 160','Lunes, miércoles y viernes de 8 a 12 hs.',null,true),
  ('Peru 1566','Peru 1566','Sin cobertura activa informada en el archivo.','BAJA A PARTIR DEL 5/6',true),
  ('Serv Warnes 1243 caba','Warnes 1243','Lunes, miércoles y viernes de 8 a 13 hs.',null,true),
  ('sp . Vte López. Libertad 1650','Libertad 1650','Lunes a viernes de 7 a 15 hs. Sábado de 9 a 13 hs.',null,true),
  ('SP Const - Pueyrredón','Av. de los Constituyentes 6020','Lunes a viernes de 9 a 13 y 17 a 22 hs. Sábado de 10 a 14 hs.',null,true),
  ('Spital Hnos','COLECTORA, Acceso Sudeste KM. 12, Los Ciruelos 3748, B1874 Sarandí','Lunes, martes, miércoles y viernes de 9 a 14 hs. Jueves de 9 a 13 hs.','BAJA',true),
  ('Virrey Olaguer y Feliu 2453 CABA','Virrey Olaguer y Feliu 2453 - Kestelboim','Lunes a sábados de 8 a 12 hs.',null,true)
on conflict(name) do update set
  address=coalesce(public.services.address,excluded.address),
  description=coalesce(public.services.description,excluded.description),
  notes=coalesce(public.services.notes,excluded.notes),
  updated_at=now();

delete from public.services s
where s.name='Consorcio Demo'
  and not exists(select 1 from public.service_stock ss where ss.service_id=s.id)
  and not exists(select 1 from public.service_extra_stock es where es.service_id=s.id)
  and not exists(select 1 from public.profiles p where p.service_id=s.id);

insert into public.materials(slug,name,category,detail,unit,image_url,critical_level,target_level,sort_order,active) values
  ('detergente-bio-ultra','Detergente ultraconcentrado','Químicos','Bio Ultra - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/detergente-bio-ultra.svg',0,1,10,true),
  ('perfume-flower','Perfume o aromatizante de piso','Químicos','Flower - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/perfume-flower.svg',0,1,20,true),
  ('lavandina-bio-lav','Lavandina líquida desinfectante','Químicos','Bio Lav - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/lavandina-bio-lav.svg',0,1,30,true),
  ('rapid-plus-gel','Lavandina en gel desinfectante','Químicos','Rapid Plus en gel - Thames · 500 ml','envase x 500 ml','assets/materials/rapid-plus-gel.svg',0,1,40,true),
  ('wood-thames','Wood','Químicos','Thames · 360 cm3','envase x 360 cm3','assets/materials/wood-thames.svg',0,1,50,true),
  ('steel-shine','Steel Shine','Químicos','Thames · 390 cm3','aerosol x 390 cm3','assets/materials/steel-shine.svg',0,1,60,true),
  ('cream-thames','Cream','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/cream-thames.svg',0,1,70,true),
  ('sarro-attack','Sarro Attack','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/sarro-attack.svg',0,1,80,true),
  ('smell-thames','Smell o aromatizante ambiental','Químicos','Thames · 262 ml','envase x 262 ml','assets/materials/smell-thames.svg',1,3,90,true),
  ('alcohol-al70','Alcohol AL70','Químicos','Thames · bidón x 5 Lts · sugerido para gimnasio','bidón x 5 Lts','assets/materials/alcohol-al70.svg',0,1,100,true),
  ('bolsas-negras-45-60','Bolsas negras 45x60','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-45-60.svg',0,1,110,true),
  ('bolsas-verdes-45-60','Bolsas verdes 45x60','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-45-60.svg',0,1,120,true),
  ('bolsas-negras-70-50','Bolsas negras 70x50','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-70-50.svg',0,1,130,true),
  ('bolsas-verdes-70-50','Bolsas verdes 70x50','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-70-50.svg',0,1,140,true),
  ('bolsas-negras-90-110','Bolsas negras 90x110','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-90-110.svg',0,1,150,true),
  ('bolsas-verdes-90-110','Bolsas verdes 90x110','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-90-110.svg',0,1,160,true),
  ('guantes-mapa-8','Guantes Mapa Talle 8','Elementos','Par de guantes','par','assets/materials/guantes-mapa-8.svg',0,1,170,true),
  ('balde-reforzado','Balde reforzado','Elementos','10 Lts','unidad','assets/materials/balde-reforzado.svg',0,1,180,true),
  ('pulverizador-gatillo','Pulverizador de 1 Lt + Gatillo','Elementos','Botella pulverizadora completa','unidad','assets/materials/pulverizador-gatillo.svg',0,2,190,true),
  ('medidor','Medidor','Elementos','Para dosificación de productos','unidad','assets/materials/medidor.svg',0,1,200,true),
  ('embudo-mediano','Embudo mediano','Elementos','Para trasvase controlado','unidad','assets/materials/embudo-mediano.svg',0,1,210,true),
  ('escoba-cabo','Escoba + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/escoba-cabo.svg',0,2,220,true),
  ('escobillon-cochera','Escobillón largo base madera + Cabo metálico','Utensilios','Para servicios con cochera','unidad','assets/materials/escobillon-cochera.svg',0,1,230,true),
  ('pala-cabo','Pala + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/pala-cabo.svg',0,1,240,true),
  ('secador-cabo','Secador + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/secador-cabo.svg',0,1,250,true),
  ('trapo-piso','Trapo de piso','Paños y fibras','Uso operativo general','unidad','assets/materials/trapo-piso.svg',0,2,260,true),
  ('rejilla','Rejilla','Paños y fibras','Uso operativo general','unidad','assets/materials/rejilla.svg',0,2,270,true),
  ('microfibra','Microfibra','Paños y fibras','Uso operativo general','unidad','assets/materials/microfibra.svg',0,2,280,true),
  ('fibra-verde','Fibra verde','Paños y fibras','Uso operativo general','unidad','assets/materials/fibra-verde.svg',0,2,290,true),
  ('esponja-acero','Esponja acero inoxidable','Paños y fibras','Uso operativo específico','unidad','assets/materials/esponja-acero.svg',0,2,300,true),
  ('esponja-amarilla','Esponja amarilla','Paños y fibras','Uso operativo general','unidad','assets/materials/esponja-amarilla.svg',0,2,310,true),
  ('plumero-microfibra','Plumero microfibra','Utensilios','Para superficies y altura baja','unidad','assets/materials/plumero-microfibra.svg',0,1,320,true),
  ('ballerina','Ballerina','Paños y fibras','Uso operativo general','unidad','assets/materials/ballerina.svg',0,2,330,true),
  ('kit-vidrios','Corderito + Secador + Agarre secador','Vidrios y altura','Kit para limpieza de vidrios','kit','assets/materials/kit-vidrios.svg',0,1,340,true),
  ('globo-telaranas','Globo para telarañas + cabo telescópico','Vidrios y altura','Cabo telescópico 2 + 2 metros','unidad','assets/materials/globo-telaranas.svg',0,1,350,true)
on conflict(slug) do update set
  name=excluded.name,category=excluded.category,detail=excluded.detail,unit=excluded.unit,
  image_url=coalesce(public.materials.image_url,excluded.image_url),sort_order=excluded.sort_order;

-- Configuración inicial de controles. Desde Administración puede editarse por insumo.
update public.materials set control_type='fractional'
where slug in('detergente-bio-ultra','perfume-flower','lavandina-bio-lav','alcohol-al70')
  and control_type='integer';

update public.materials set control_type='quantity_condition'
where slug in('trapo-piso','rejilla','microfibra','fibra-verde','esponja-acero','esponja-amarilla','ballerina')
  and control_type='integer';

-- Después de crear tu usuario en Authentication, promoverlo a administrador:
-- update public.profiles set role='admin',full_name='Administrador Clean It' where email='TU-CORREO@DOMINIO.COM';
